spring:
  application:
    name: CouponService # very important as it is the id of the service.
  config-server:
    # Notice the URL is removed! It just specifies the protocol now.
    import-path: "optional:configserver:"
    # This tells the import to look up the Config Server in Eureka
server:
  port: 8081   # Each service must have unique port

eureka:
  server:
    url: http://localhost:8761/eureka/ # the url of the service registry server.
    hostname: localhost