spring:
  application:
    name: CouponService # very important as it is the id of the service.

server:
  port: 8081   # Each service must have unique port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # the url of the service registry server.
  instance:
    hostname: localhost