spring:
  application:
    name: CouponService
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ConfigServer
  config:
    import: "optional:configserver:" # Remember to keep this lowercase!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # the url of the service registry server.
  instance:
    hostname: localhost