# resilience4j retries configuration
ProductService:
  name: ProductsService # very important as it is the id of the service.
  port: 8090   # Each service must have unique port
  eureka:
    server:
      url: http://localhost:8761/eureka/ # the url of the service registry server.
      hostname: localhost
  resilience4j:
    retry:
      instances:
        getProductRetry:
          maxAttempts: 3              # Total 3 attempts (1 initial + 2 retries)
          waitDuration: 1s            # Wait 1 second between retries